//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2QXRunning.Ressources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RessourcesViewModels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RessourcesViewModels() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_2QXRunning.Ressources.RessourcesViewModels", typeof(RessourcesViewModels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Categorie de la course.
        /// </summary>
        public static string CategorieCourse {
            get {
                return ResourceManager.GetString("CategorieCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date de depart.
        /// </summary>
        public static string DateDepart {
            get {
                return ResourceManager.GetString("DateDepart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prénom.
        /// </summary>
        public static string firstName {
            get {
                return ResourceManager.GetString("firstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dans les 12 prochains mois.
        /// </summary>
        public static string intervalle_12ProchainsMois {
            get {
                return ResourceManager.GetString("intervalle_12ProchainsMois", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dans les 30 prochains jours.
        /// </summary>
        public static string intervalle_30ProchainsJours {
            get {
                return ResourceManager.GetString("intervalle_30ProchainsJours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dans les 6 prochains mois.
        /// </summary>
        public static string intervalle_6ProchainsMois {
            get {
                return ResourceManager.GetString("intervalle_6ProchainsMois", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le Week-End prochain.
        /// </summary>
        public static string intervalle_weekEndProchain {
            get {
                return ResourceManager.GetString("intervalle_weekEndProchain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom.
        /// </summary>
        public static string lastName {
            get {
                return ResourceManager.GetString("lastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La categorie est obligatoire.
        /// </summary>
        public static string required_CategorieCourse {
            get {
                return ResourceManager.GetString("required_CategorieCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Un créateur est obligatoire..
        /// </summary>
        public static string required_Createur {
            get {
                return ResourceManager.GetString("required_Createur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La date est obligatoire..
        /// </summary>
        public static string required_Date {
            get {
                return ResourceManager.GetString("required_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La description est obligatoire..
        /// </summary>
        public static string required_Description {
            get {
                return ResourceManager.GetString("required_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Un evenement est obligatoire..
        /// </summary>
        public static string required_Evenement {
            get {
                return ResourceManager.GetString("required_Evenement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le prénom est obligatoire..
        /// </summary>
        public static string required_firstName {
            get {
                return ResourceManager.GetString("required_firstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le nom est obligatoire..
        /// </summary>
        public static string required_lastName {
            get {
                return ResourceManager.GetString("required_lastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le libellé est obligatoire..
        /// </summary>
        public static string required_Libelle {
            get {
                return ResourceManager.GetString("required_Libelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le statut est obligatoire..
        /// </summary>
        public static string required_Statut {
            get {
                return ResourceManager.GetString("required_Statut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le tarif est obligatoire..
        /// </summary>
        public static string required_Tarif {
            get {
                return ResourceManager.GetString("required_Tarif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le titre est obligatoire..
        /// </summary>
        public static string required_Titre {
            get {
                return ResourceManager.GetString("required_Titre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Un type de manifestion est obligatoire..
        /// </summary>
        public static string required_TypeManifestation {
            get {
                return ResourceManager.GetString("required_TypeManifestation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La ville est obligatoire..
        /// </summary>
        public static string required_Ville {
            get {
                return ResourceManager.GetString("required_Ville", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type de manifestation.
        /// </summary>
        public static string TypeManifestation {
            get {
                return ResourceManager.GetString("TypeManifestation", resourceCulture);
            }
        }
    }
}
